= Conclusiones
Este capítulo relata las conclusiones del proyecto que ofrecen los objetivos propuestos, @sec:projectconclusions, así como el punto de vista personal del autor, @sec:ownconclusions, revelando los próximos pasos y delegando requisitos y pinceladas funcionales en trabajos futuros, @sec:future-work.

== Conclusiones del Proyecto <sec:projectconclusions>
El documento ha recorrido el estado del arte, el plan de proyecto, el análisis, el diseño, la implementación y la verificación de una aplicación web de gestión del conocimiento multilingüe, culminando con una propuesta teórica de exposición pública, todo ello al amparo de estándares y marcos internacionales a destacar como ISO/IEC/IEEE 29148 @isoieee29148, ISO/IEC/IEEE 15288 @isoieee15288, el Modelo C4 @c4model y el OWASP Top 10 GenIA/LLM @owasp. La @sec:objetivos anuncia el propósito principal consistente en diseñar y desarrollar un sistema del conocimiento multilingüe basado en @glossllm que actúe como alternativa accesible y de código abierto a las herramientas tradicionales. OntoNova cumple dicho propósito, con los requisitos incluidos y verificados en la @sec:verifyreqs, pruebas automáticas superadas, @sec:verifysummary, y una validación con usuarios reales por encima del umbral de usabilidad comprometido, @sec:verifyanalysis.

#par(first-line-indent: 0pt)[
Adicionalmente, todos los objetivos secundarios han sido cumplidos:
]

- *O1:* El aprendizaje alcanzado supera el nivel tres exigido de la taxonomía de Bloom @bloomstaxonomy, porque el conocimiento adquirido no solo se aplica, la decodificación guiada estudiada en la @sec:determinism queda convertida en el proceso multi-agente de la @sec:agentpipeline, sino que también se analiza y evalúa, como demuestran el diagnóstico de comportamientos del motor de inferencia y de su ausencia de determinismo entre sesiones, @sec:challenges, y las campañas estadísticas de calidad diseñadas a medida para caracterizarlo, @sec:verifysummary.
- *O2:* La barrera de entrada disminuye de manera medible. La escala de usabilidad arroja una media de 76,5 sobre el umbral comprometido de 70, @sec:verifyanalysis, con el matiz revelador de que las puntuaciones elevadas provienen de participantes sin formación técnica ni conocimiento previo de las ontologías. Cabe resaltar que cada operación de edición se completa en tres interacciones o menos, @sec:verifydemonstration, y la generación parte de texto libre en el idioma del experto, disolviendo el problema del lienzo en blanco para los ingenieros de conocimiento que motiva el proyecto, @sec:motivacion.
- *O3:* El carácter multilingüe queda verificado con REQ-US-FC-01 acompañado de generaciones reales repartidas entre inglés y español con detección automática del idioma, @sec:verifysummary, extendiéndose a la interfaz y a los errores del servicio, traducidos ambos al idioma del usuario, @sec:eventdesign.
- *O4:* El cumplimiento del marco regulatorio europeo vigente @edpb2025ai (p. ej., @glossgdpr @gdpr y @glossaiact @aiactlaw) dispone de una verificación dedicada, @sec:verifyregulation, con el veredicto favorable del verificador de conformidad reproducido en el @app:aiact, la privacidad garantizada por diseño al no abandonar los datos el equipo del experto, @sec:securitydesign, y el consiguiente impacto normativo en el escenario público, @sec:cloudlaw.
- *O5:* La arquitectura se diseña y documenta con el Modelo C4 @c4model en sus tres niveles, @sec:architecture, incorpora las mitigaciones de seguridad frente a los riesgos de las aplicaciones que hacen uso de @glossllm, @sec:securitydesign, y aplica patrones de diseño @gangoffour como el principio de responsabilidad única por agente @cleanarchitecture[Cap. 7] y el principio abierto/cerrado @cleanarchitecture[Cap. 8], verificado este último por inspección junto a la escalabilidad sin rediseño que otorga la ausencia de estado, @sec:verifyinspection, proyectada después sobre la nube pública en el @sec:cloud.
- *O6:* La alineación con los Objetivos de Desarrollo Sostenible, @sec:odslaw, queda revelada con el desarrollo y validación del sistema completo sobre _hardware_ doméstico, @sec:dev, preservando la soberanía tecnológica y demostrando una barrera de entrada alcanzable @ods[ODS 10]. En segundo lugar, la democratización perseguida está evidenciada por los perfiles diversos que lo utilizaron con éxito, @sec:verifyanalysis. En tercer lugar, el aprendizaje adquirido en el proyecto @ods[ODS 4], director de orquesta de principio a fin, @sec:methodology, queda ligado al objetivo O1. En última instancia, el marco de innovación @ods[ODS 9] engloba el proyecto de OntoNova por su unicidad frente a otros competidores semánticos, @sec:sbcaialternatives, un sistema que espera una patente de dicho ámbito y futuras mejoras en cuanto se ponga a disposición de la comunidad @glossfoss @osiosd.

El proceso de aprendizaje ha marcado cada ciclo de imprecisión-decisión de diseño, @sec:designtenets, e implementación, @sec:challenges, con el propósito de ofrecer al autor una retroalimentación y nuevos conocimientos, @sec:ownconclusions.

#pagebreak()
== Conclusiones Personales <sec:ownconclusions>
Reforzando la idea introducida en el @sec:intro de introducción, el desarrollo de este proyecto me ha permitido tener la oportunidad de exclamar al mundo qué conocimientos he aprendido a lo largo de la carrera, el máster y la trayectoria profesional, y unirlos en un nuevo aprendizaje para formar, en última instancia, una solución que pueda facilitar la construcción multilingüe de conocimiento a los verdaderos expertos del dominio. Especialmente, me entusiasma haber podido llevar a cabo un proyecto que me ha involucrado en todas y cada una de sus fases, desde el análisis inicial hasta la implementación final. Se trata de una práctica que apenas estoy comenzando a ejercitar en el ámbito laboral, y poder ser partícipe de un ciclo de desarrollo completo me ha servido para reforzar los conocimientos y la confianza necesarios para retomar mi carrera profesional con más fuerza que nunca.

Asimismo, no puedo evitar sentirme afortunado de haber cursado la carrera en ausencia de la @glossai:long. Cuando comencé la presente titulación de máster en 2024 ya se apreciaban los primeros coletazos de la @glossai generativa y agéntica, la cual ha cambiado el mundo drásticamente ---para bien--- en 2026. Sin embargo, siento que, si tuviera que repetir las titulaciones hoy en día, me perdería muchas experiencias y aprendizajes que he podido vivir precisamente gracias a su ausencia.

Asignaturas como Calidad de Software y Sistemas, Sistemas de Ciberseguridad, Software para Internet de las cosas y Aplicaciones Avanzadas de la Inteligencia Artificial han fortalecido la base de mi conocimiento actual y han servido de inspiración para seguir mi travesía por el mundo digital con el mismo objetivo de siempre: "Estudiar y ser partícipe de todas las ramas de la informática que el mundo pueda ofrecer".

== Trabajos Futuros <sec:future-work>
Los capítulos precedentes señalan, allí donde surgen, las líneas que exceden los objetivos comprometidos, @sec:objetivos, y los requisitos incluidos, @sec:requirementexposition. La consolidación se presenta en tres planos, el funcional que heredan los requisitos no incluidos, el de la calidad de generación y el normativo-operativo, cerrando con el trabajo propuesto.

#par(first-line-indent: 0pt)[
En el plano funcional, los requisitos en estado viable o pendientes de una nueva fase de diseño trazan la evolución natural del producto:
]

- *Persistencia y colaboración.* La incorporación del contenedor de persistencia, anotada en la @sec:c4containers, habilita la edición simultánea con convergencia del estado compartido, REQ-US-FC-06, y el histórico de versiones con reversión y auditoría de cambios, REQ-US-FC-07.
- *Importación de ontologías.* El camino inverso a la exportación verificada en REQ-US-FC-05, @sec:verifytest, es decir, cargar ontologías existentes en formatos @glossw3c sin pérdida de tripletas, REQ-US-FC-08, reclama una fase de diseño que reconcilie grafos externos con el contrato de la @sec:datacontract.
- *Expresividad del contrato.* La ampliación gradual del perfil de @glossowl con las restricciones de cardinalidad, las clases anónimas y los axiomas de equivalencia, anotada en la @sec:datacontract, sin coste estructural gracias al campo de metadatos.
- *Accesibilidad, soporte y cobertura.* La conformidad de nivel AA con las @glosswcag:long @wcag2, REQ-SW-NF-01, el sistema de soporte con su plan de mantenimiento, REQ-US-NF-03, y la superación del umbral de cobertura de las pruebas automáticas, REQ-SW-NF-04, atributos que un prototipo verificado aún no reclama.

En el plano de la calidad de generación, las campañas de la @sec:verifysummary y las dificultades de la @sec:challenges acotan empíricamente dónde invertir:

- *Refinamiento de instrucciones.* Las categorías débiles del dominio denso ---la jerarquía y las aserciones entre individuos--- señalan el objetivo del refinamiento delegado por la @sec:verifysummary, con las métricas clásicas como vara de medir cada iteración.
- *Modelos de mayor capacidad.* La brecha entre la puntuación perfecta del dominio liviano y el 0,41 de F1 del denso apunta a la capacidad del modelo como techo, hipótesis contrastable en el grupo de nodos de inferencia que propone la @sec:clouddeploy y evaluable bajo las pruebas declaradas en la @sec:verifysummary.
- *Conectividad y documentos extensos.* El suelo de calidad ensayado y descartado con datos en la @sec:challenges requiere una teoría alternativa para las clases huérfanas, y el límite de entrada de REQ-US-FC-01 invita a una estrategia de división y consolidación que procese documentos más allá de los 15.000 caracteres.

En el plano normativo-operativo, la exposición pública dispone del @sec:cloud al completo, donde la identidad y la trazabilidad reciben su encaje arquitectónico, adelantando la fase de diseño de los requisitos REQ-US-FC-09, REQ-SW-NF-07 y REQ-SW-FC-01. El despliegue automatizado se detalla etapa a etapa y el impacto legal se analiza, dejando su implementación a un único paso de distancia del presente trabajo. Asimismo, la exposición pública activa obligaciones que son latentes en la solución local:

- *Reevaluación de conformidad.* La caída de las exclusiones del @glossaiact:long al publicarse, comprometida en la @sec:verifyregulation y analizada en la @sec:cloudlaw, convierte la repetición del cuestionario del @app:aiact en el primer entregable de una futura explotación.
- *Información pública obligatoria.* El aviso legal y la declaración de política de privacidad dentro de OntoNova, exigidos por el compromiso de información mínima de la licencia @glosseupl señalado en la @sec:cloudlaw.