#let genai-declaration = (
  usage: true, // true: used with authorization; false: not used
  data-usage: (
    confidential: false,
    copyright: false,
    personal: false,
    tos: true, // Did your usage respect the tool's terms of use?
  ),
  technical-usage: (
    tool: "Claude Sonnet 5",
    // Name of the AI system/tool and version (e.g. "ChatGPT 4o", "Gemini 2.0")
    // tool: "ChatGPT 4o",
    // If you think it is necessary to include it, add it in each case:
    // *using the prompt* ...
    //            (write the request made to the AI)
    // *having as interaction* ...
    //            (describe what interaction you made with the AI after the
    //            prompt's response)
    //
    // Example: I declare that I have made use of the Generative AI system
    // Chat GPT 3.5 to search for information using the prompt: "Tell me a
    // concrete example that illustrates the application of the urban planning
    // proposal of the 15-minute City in Spain", having as interaction the
    // proposition of the concrete example of the Chamartín district that has
    // been reflected in the report.
    //
    // ── Documentation and drafting ────────────────────────────────────────
    // Comment out the ones that don't apply.
    //documentation: [_[Add an example] For example: I have asked for a list of
    //  alternatives to address the problem stated at the beginning of the paper._],
    //reflection: [_[Add an example] For example: I have asked for a list of
    //  alternatives to address the problem stated at the beginning of the paper._],
    //review: [_[Add an example] For example: I have asked for paragraphs to be
    //  rewritten to shorten the conclusions while keeping the same ideas already
    //  written._],
    //research: [_[Add an example] For example: The questions asked were aimed at
    // [finding definitions, explanations of processes, examples of use, lists of
    //  risks of use...]._],
    references: [
      Ejemplo 1. *Utilizando la instrucción*: "¿Qué libro, artículo o fuente oficial introduce el concepto de la piramide de testing?", *teniendo como interacción* la declaración de la fuente y el año de publicación del libro _Succeeding with Agile_ de Mike Cohn, 2009, en unión a una breve explicación de la pirámide y su relación con la metodología ágil.
      Ejemplo 2. *Utilizando la instrucción*: "¿Quién introduce el concepto de Shift Left? Porque la pirámide de testing parece contribuira ello", *teniendo como interacción* la mención de la fuente y el año de publicación del artículo de revista _Shift Left Testing_ de Larry Smith, 2001, en conjunto con una explicación de la relación entre ambos conceptos.
    ],
    summary: [
      Ejemplo 1. *Utilizando la instrucción*: "Revisa Arquitectura Limpia de C.Martin y extrae el índice de contenidos pues me gustaría citarlo en un requisito de diseño que menciona el escalado horizontal", *teniendo como interacción* la propuesta del capítulo 10 del libro con un resumen del mismo.
    ],
    //translation: [_Translation of texts consulted._],
    // ── Develop specific content ───────────────────────────────────────────
    assistance-coding: [
      Ejemplo 1. *Utilizando la instrucción*: "Could you prepare a playwright e2e test passing the application these Domain 2 PDF of less than 5MB and compare the results with these Domain 1 metrics so we can test agent chain performance?", *teniendo como interacción* la propuesta de construcción de una prueba cuya ejecución destapa un tipo MIME incorrecto, la desalineación de instrucciones y colisiones de identificadores.
    ],
    //generating-content: [_[indicate its use in this section, as well as in a
    //  footnote to the figure/element generated by Generative AI] For example:
    //  Source: own elaboration with the help of Midjourney._],
    optimization: [
      Ejemplo 1. *Utilizando la instrucción*: "Given nexolabs.txt which its ontology generation is failing with the error 'Malformed LLM response from http://vllm:8000/v1: Expecting ',' delimiter: line 20709 column 1 (char 39087)', please analyze these python snippets and provide a STDOUT solution", *teniendo como interacción* el diagnóstico razonado de la causa raíz del error enlazado a propuestas de optimizaciones secundarias como secuencias de parada, la detección de truncamiento y la ampliación de reparaciones del validador determinista.
    ],
    //data-processing: [_[Add an example] For example: after collecting the data,
    //  I have asked for guidance in normalising the data in preparation for the
    //  subsequent analysis._],
    //idea-inspiration: [_[Add an example] For example: once I was clear about the
    //  objective of the work, I asked for ideas to cover the project from a
    //  multidisciplinary approach._],
    //other: [_Other uses linked to the generation of specific points of the
    //  specific development of the work._],
  ),
  usage-reflection: [
    El uso de la inteligencia artificial generativa en este trabajo es coherente con el sentimiento expuesto en las conclusiones personales de la memoria, donde me declaro afortunado de haberme formado en el sistema educativo en su ausencia. Mantengo un rechazo absoluto a que la inteligencia artificial generativa participe en las fases de innovación e imaginación de un proyecto, pues considero que la concepción de ideas, la motivación y las decisiones creativas son íntegramente humanas. En esta iniciativa, toda propuesta arquitectónica nace de mi criterio en base a las necesidades expuestas por mi gerente de proyecto ---la tutora---, y la herramienta se limita a asistir en su implementación. Su fortaleza diferencial la encuentro, en cambio, en el ámbito de la calidad del software. Como asistente de pruebas ha demostrado una capacidad de sobreanalizar casos de uso, casos límite y condiciones de carrera que adelanta la detección de defectos a fases tan tempranas del ciclo de vida que hasta el enfoque de desplazamiento a la izquierda da las gracias por ello. Como debilidad, señalo la necesidad permanente de supervisión, pues la herramienta puede errar con facilidad ---bibliografía incluida---, lo que me empuja a verificar las salidas propuestas con una disciplina que, lejos de ser un coste, ha reforzado mi propio aprendizaje, obligándome a comprender cada corrección antes de aceptarla.
  ],
)
